### ISSUE TITLE
Refonte graphique de G.A.R.I.

### ISSUE THREAD

**Issue by Azurency** [Azurency/gari#54]
La refonte va permettre d'apporter de la cohérence et plus de visibilité dans G.A.R.I.
*Cette issue rassemble toutes les issue relatives à la refonte graphique*

**Roadmap :** 
- [x] Revoir la sidebar #52 
- [x] Design des boutons
- [x] Revoir le design de sweetalert2
- [x] Refonte du sélecteur de date pikaday
- [x] Ajouter des couleurs dans le tableau d'affectation #53
- [x] Revoir l'affichage des boutons de la page d'affectation (valider, etc.)
- [x] Mise en forme des totaux de véhicules en réserve
- [x] Design du message quand l'affectation est validée
- [x] Ajout d'un effet au survol des lignes des tableaux (pour repérer où on en est)
- [x] Refonte des formulaires

**Idées :**

- Ajouter les indisponibilités directement depuis une fenêtre sweetalert2 et ne pas passer par une page intermédiaire (plus cohérent avec le reste de l'application)
- Passer les `select` en champs avec autocomplete (permet de saisir au clavier plus facilement, car l'utilisateur a tendance sinon à utiliser la souris)
